feat(3491503520): Disable deploy if wallet is not connected
starkware-libs/cairo-playground pull request #33
Opened 2023-01-24 11:56 UTC by galuzan-starkware

### Description of the Changes

- Disable deploy button 

Solves #[3491503520](https://starkware.monday.com/boards/2847513897/pulses/3491503520)

---

### Checklist

- [ ] Manually tests of the main Application flows are done and passed.
- [ ] New unit / functional tests have been added (whenever applicable).
- [ ] Docs have been updated (whenever relevant).
- [ ] PR title is follow the [Conventional Commits](https://www.conventionalcommits.org/) convention: `<type>[optional scope]: <description>`, e.g: `fix: prevent racing of requests`

2023-01-31 09:27 UTC, dan-ziv requested changes

2023-01-31 09:27 UTC, dan-ziv commented on src/components/Features/Editor/EditorButtons/EditorButtons.js
> +        isDisabled: !isCairoMode && !account,
Why do we need the `!isCairoMode`?

2023-01-31 10:56 UTC, galuzan-starkware commented on src/components/Features/Editor/EditorButtons/EditorButtons.js
> +        isDisabled: !isCairoMode && !account,
done

2023-01-31 11:31 UTC, dan-ziv submitted a review, later dismissed

2023-02-07 15:35 UTC, dan-ziv approved these changes

2023-02-07 15:36 UTC, merged

2023-02-07 15:37 UTC, dan-ziv commented
:tada: This PR is included in version 0.1.0-dev.2 :tada:

The release is available on [GitHub release](https://github.com/starkware-libs/cairo-playground/releases/tag/v0.1.0-dev.2)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: